# Generated by Django 5.1.6 on 2025-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rfpuserdetails_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpvendordetail',
            name='vendor_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('Rejected', 'Rejected')], default='Rejected', max_length=10),
        ),
    ]
