# Generated by Django 5.1.6 on 2025-03-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rfpvendordetail_vendor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('last_date', models.DateField()),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('quanity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rfpcategories')),
            ],
        ),
    ]
