# Generated by Django 5.1.6 on 2025-04-01 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rfplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfplist',
            name='admin',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfplist',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
