# Generated by Django 5.1.6 on 2025-04-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rfplist_admin_alter_rfplist_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfplist',
            name='admin',
        ),
    ]
