# Generated by Django 5.1.6 on 2025-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_rfplist_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfplist',
            name='last_date',
            field=models.DateField(),
        ),
    ]
