# Generated by Django 5.1.6 on 2025-04-01 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_rfplist_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfplist',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
