# Generated by Django 5.1.6 on 2025-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_rfplist_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfplist',
            name='last_date',
            field=models.DateField(auto_now=True),
        ),
    ]
