# Generated by Django 5.1.6 on 2025-04-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_rfplist_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfplist',
            name='last_date',
        ),
    ]
