# Generated by Django 5.1.6 on 2025-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_rfplist_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfplist',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=10),
        ),
    ]
