# Generated by Django 5.1.6 on 2025-04-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rfplist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('item_description', models.TextField()),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rfplist')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rfpvendordetail')),
            ],
        ),
    ]
