# Generated by Django 5.1.6 on 2025-04-02 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rfpquotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfplist',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
